[package]
name = "hep-framework"
version = "0.5.0"
authors = ["Aldey Wahyu Putra <al.arudei01@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unroll = "0.1.5"
